[package]
name = "cfvm"
version = "0.1.0"
authors = ["Lyzh <enterindex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emei = "^0.3.0"

lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"