[package]
name = "selection_dag"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfvm_common = { path="../cfvm_common" }
cfir = { path="../cfir" }